package com.done.struts.form;

import java.util.Date;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.validator.ValidatorForm;


/**
 * Basket generated by MyEclipse Persistence Tools
 */

public class BasketForm extends ValidatorForm {
	//扩展属性
	private String count;
	private String action;
	// Fields

	private Integer basketId;

	private String hwId;

	private String userName;

	private String basketCount;

	private Date basketDate;

	private String basketCheck;

	private String basketAdmincheck;

	private String hwName;

	private String hwCash;

	private String subNumber;

	private String daili;

	// Constructors

	/** default constructor */
	public BasketForm() {
	}

	/** minimal constructor */
	public BasketForm(Integer basketId) {
		this.basketId = basketId;
	}


	public Integer getBasketId() {
		return this.basketId;
	}

	public void setBasketId(Integer basketId) {
		this.basketId = basketId;
	}

	public String getHwId() {
		return this.hwId;
	}

	public void setHwId(String hwId) {
		this.hwId = hwId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getBasketCount() {
		return this.basketCount;
	}

	public void setBasketCount(String basketCount) {
		this.basketCount = basketCount;
	}

	public Date getBasketDate() {
		return this.basketDate;
	}

	public void setBasketDate(Date basketDate) {
		this.basketDate = basketDate;
	}

	public String getBasketCheck() {
		return this.basketCheck;
	}

	public void setBasketCheck(String basketCheck) {
		this.basketCheck = basketCheck;
	}

	public String getBasketAdmincheck() {
		return this.basketAdmincheck;
	}

	public void setBasketAdmincheck(String basketAdmincheck) {
		this.basketAdmincheck = basketAdmincheck;
	}

	public String getHwName() {
		return this.hwName;
	}

	public void setHwName(String hwName) {
		this.hwName = hwName;
	}

	public String getHwCash() {
		return this.hwCash;
	}

	public void setHwCash(String hwCash) {
		this.hwCash = hwCash;
	}

	public String getSubNumber() {
		return this.subNumber;
	}

	public void setSubNumber(String subNumber) {
		this.subNumber = subNumber;
	}

	public String getDaili() {
		return this.daili;
	}

	public void setDaili(String daili) {
		this.daili = daili;
	}
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=new ActionErrors();
		//errors.add("Name",new ActionMessage("error.Name.required"));
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		
	}


	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

}