package com.done.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * News generated by MyEclipse Persistence Tools
 */

public class NewsForm extends ValidatorForm {

    // Fields

    private Integer newsId;

    private String newsTitle;

    private String newsContent;

    private Date newsDate;

    private Integer status;

    private String userId;

    private String userName;

    // Constructors

    /** default constructor */
    public NewsForm() {
    }

    /** minimal constructor */
    public NewsForm(Integer newsId) {
        this.newsId = newsId;
    }

    /** full constructor */
    public NewsForm(Integer newsId, String newsTitle, String newsContent, Date newsDate, String userId, String userName) {
        this.newsId = newsId;
        this.newsTitle = newsTitle;
        this.newsContent = newsContent;
        this.newsDate = newsDate;
        this.userId = userId;
        this.userName = userName;
    }

    @Override
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {

        return null;
    }

    /**
     * Method reset
     * 
     * @param mapping
     * @param request
     */
    @Override
    public void reset(ActionMapping mapping, HttpServletRequest request) {

    }

    // Property accessors

    public Integer getNewsId() {
        return this.newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public String getNewsTitle() {
        return this.newsTitle;
    }

    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    public String getNewsContent() {
        return this.newsContent;
    }

    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }

    public Date getNewsDate() {
        return this.newsDate;
    }

    public void setNewsDate(Date newsDate) {
        this.newsDate = newsDate;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}