
package com.legendshop.ws.service.product;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-03T23:02:19.495+08:00
 * Generated source version: 2.6.1
 * 
 */
public final class ProductService_ProductServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://product.service.ws.legendshop.com", "ProductService");

    private ProductService_ProductServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProductService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductService_Service ss = new ProductService_Service(wsdlURL, SERVICE_NAME);
        ProductService port = ss.getProductServicePort();  
        
        {
        System.out.println("Invoking importProductService...");
        com.legendshop.ws.service.product.Product _importProductService_product = null;
        java.lang.String _importProductService__return = port.importProductService(_importProductService_product);
        System.out.println("importProductService.result=" + _importProductService__return);


        }

        System.exit(0);
    }

}
