package com.legendshop.ws.service.product;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-03T23:02:19.625+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "ProductService", 
                  wsdlLocation = "http://localhost:81/legendshop_ws/services/productService?wsdl",
                  targetNamespace = "http://product.service.ws.legendshop.com") 
public class ProductService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://product.service.ws.legendshop.com", "ProductService");
    public final static QName ProductServicePort = new QName("http://product.service.ws.legendshop.com", "ProductServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:81/legendshop_ws/services/productService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:81/legendshop_ws/services/productService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductService getProductServicePort() {
        return super.getPort(ProductServicePort, ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductService getProductServicePort(WebServiceFeature... features) {
        return super.getPort(ProductServicePort, ProductService.class, features);
    }

}
