package com.done.model;

import java.util.Date;

/**
 * Basket generated by MyEclipse Persistence Tools
 */

public class Basket implements java.io.Serializable {
    //扩展属性

    private Double total;//=单价*数量
    // Fields

    private Integer basketId;

    private String hwId;

    private String userName;

    private String basketCount;

    private String basketCheck;

    private String basketAdmincheck;

    private String hwName;

    private String hwPrice;

    private String hwCash;

    private String subNumber;

    private Date basketDate;

    private String shopName;

    // Constructors

    /** default constructor */
    public Basket() {
    }

    /** minimal constructor */
    public Basket(Integer basketId) {
        this.basketId = basketId;
    }

    /** full constructor */
    public Basket(Integer basketId, String hwId, String userName, String basketCount, String basketCheck,
            String basketAdmincheck, String hwName, String hwPrice, String hwCash, String subNumber, Date basketDate) {
        this.basketId = basketId;
        this.hwId = hwId;
        this.userName = userName;
        this.basketCount = basketCount;
        this.basketCheck = basketCheck;
        this.basketAdmincheck = basketAdmincheck;
        this.hwName = hwName;
        this.hwPrice = hwPrice;
        this.hwCash = hwCash;
        this.subNumber = subNumber;
        this.basketDate = basketDate;
    }

    // Property accessors

    public Integer getBasketId() {
        return this.basketId;
    }

    public void setBasketId(Integer basketId) {
        this.basketId = basketId;
    }

    public String getHwId() {
        return this.hwId;
    }

    public void setHwId(String hwId) {
        this.hwId = hwId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getBasketCount() {
        return this.basketCount;
    }

    public void setBasketCount(String basketCount) {
        this.basketCount = basketCount;
    }

    public String getBasketCheck() {
        return this.basketCheck;
    }

    public void setBasketCheck(String basketCheck) {
        this.basketCheck = basketCheck;
    }

    public String getBasketAdmincheck() {
        return this.basketAdmincheck;
    }

    public void setBasketAdmincheck(String basketAdmincheck) {
        this.basketAdmincheck = basketAdmincheck;
    }

    public String getHwName() {
        return this.hwName;
    }

    public void setHwName(String hwName) {
        this.hwName = hwName;
    }

    public String getHwPrice() {
        return this.hwPrice;
    }

    public void setHwPrice(String hwPrice) {
        this.hwPrice = hwPrice;
    }

    public String getHwCash() {
        return this.hwCash;
    }

    public void setHwCash(String hwCash) {
        this.hwCash = hwCash;
    }

    public String getSubNumber() {
        return this.subNumber;
    }

    public void setSubNumber(String subNumber) {
        this.subNumber = subNumber;
    }

    public Date getBasketDate() {
        return this.basketDate;
    }

    public void setBasketDate(Date basketDate) {
        this.basketDate = basketDate;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

}