package com.done.model;

import java.util.Date;

/**
 * HwComment generated by MyEclipse Persistence Tools
 */

public class HwComment implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer hwId;

	private String userId;

	private String content;

	private Date addtime;

	private String postip;

	private Short score;

	// Constructors

	/** default constructor */
	public HwComment() {
	}

	/** minimal constructor */
	public HwComment(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public HwComment(Integer id, Integer hwId, String userId, String content,
			Date addtime, String postip, Short score) {
		this.id = id;
		this.hwId = hwId;
		this.userId = userId;
		this.content = content;
		this.addtime = addtime;
		this.postip = postip;
		this.score = score;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getHwId() {
		return this.hwId;
	}

	public void setHwId(Integer hwId) {
		this.hwId = hwId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public String getPostip() {
		return this.postip;
	}

	public void setPostip(String postip) {
		this.postip = postip;
	}

	public Short getScore() {
		return this.score;
	}

	public void setScore(Short score) {
		this.score = score;
	}

}