package com.done.model;

import java.util.Date;

/**
 * HwDetail generated by MyEclipse Persistence Tools
 */

public class HwDetail implements java.io.Serializable {

    private Integer hwId;

    private Integer sortId;

    private Integer nsortId;

    private Integer subNsortId;

    private String hwName;

    private Long hwPrice;

    private Long hwCash;

    private String hwBrief;

    private String hwContent;

    private Integer hwViews;

    private Integer hwBuys;

    private Date hwDate;

    private String hwPic;

    private String commend;

    private Integer status;

    private Date modifyDate;

    private String userId;

    private String userName;

    private String sortName;

    private String nsortName;

    private String subNsortName;

    public String getCommend() {
        return commend;
    }

    public void setCommend(String commend) {
        this.commend = commend;
    }

    public String getHwBrief() {
        return hwBrief;
    }

    public void setHwBrief(String hwBrief) {
        this.hwBrief = hwBrief;
    }

    public Integer getHwBuys() {
        return hwBuys;
    }

    public void setHwBuys(Integer hwBuys) {
        this.hwBuys = hwBuys;
    }

    public Long getHwCash() {
        return hwCash;
    }

    public void setHwCash(Long hwCash) {
        this.hwCash = hwCash;
    }

    public String getHwContent() {
        return hwContent;
    }

    public void setHwContent(String hwContent) {
        this.hwContent = hwContent;
    }

    public Date getHwDate() {
        return hwDate;
    }

    public void setHwDate(Date hwDate) {
        this.hwDate = hwDate;
    }

    public Integer getHwId() {
        return hwId;
    }

    public void setHwId(Integer hwId) {
        this.hwId = hwId;
    }

    public String getHwName() {
        return hwName;
    }

    public void setHwName(String hwName) {
        this.hwName = hwName;
    }

    public String getHwPic() {
        return hwPic;
    }

    public void setHwPic(String hwPic) {
        this.hwPic = hwPic;
    }

    public Long getHwPrice() {
        return hwPrice;
    }

    public void setHwPrice(Long hwPrice) {
        this.hwPrice = hwPrice;
    }

    public Integer getHwViews() {
        return hwViews;
    }

    public void setHwViews(Integer hwViews) {
        this.hwViews = hwViews;
    }

    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public Integer getNsortId() {
        return nsortId;
    }

    public void setNsortId(Integer nsortId) {
        this.nsortId = nsortId;
    }

    public String getNsortName() {
        return nsortName;
    }

    public void setNsortName(String nsortName) {
        this.nsortName = nsortName;
    }

    public Integer getSortId() {
        return sortId;
    }

    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    public String getSortName() {
        return sortName;
    }

    public void setSortName(String sortName) {
        this.sortName = sortName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getSubNsortId() {
        return subNsortId;
    }

    public void setSubNsortId(Integer subNsortId) {
        this.subNsortId = subNsortId;
    }

    public String getSubNsortName() {
        return subNsortName;
    }

    public void setSubNsortName(String subNsortName) {
        this.subNsortName = subNsortName;
    }

}