package com.done.model;

import java.util.Date;

/**
 * Myfavorite generated by MyEclipse Persistence Tools
 */

public class Myfavorite implements java.io.Serializable {

	// Fields

	private String id;

	private String hwId;

	private String hwName;

	private Date addtime;

	private String memo;

	// Constructors

	/** default constructor */
	public Myfavorite() {
	}

	/** minimal constructor */
	public Myfavorite(String id) {
		this.id = id;
	}

	/** full constructor */
	public Myfavorite(String id, String hwId, String hwName, Date addtime,
			String memo) {
		this.id = id;
		this.hwId = hwId;
		this.hwName = hwName;
		this.addtime = addtime;
		this.memo = memo;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHwId() {
		return this.hwId;
	}

	public void setHwId(String hwId) {
		this.hwId = hwId;
	}

	public String getHwName() {
		return this.hwName;
	}

	public void setHwName(String hwName) {
		this.hwName = hwName;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}