package com.done.model;

import java.util.Date;

/**
 * Myleague generated by MyEclipse Persistence Tools
 */

public class Myleague implements java.io.Serializable {

	// Fields

	private Integer id;

	private String userId;

	private String friendId;

	private String friendName;

	private Integer displayOrder;
	
	private String banner;
	
	public Myleague(String friendId, String friendName, String banner) {
		this.friendId = friendId;
		this.friendName = friendName;
		this.banner = banner;
	}

	public String getBanner() {
		return banner;
	}

	public void setBanner(String banner) {
		this.banner = banner;
	}

	public Integer getDisplayOrder() {
		return displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	private Integer status;

	private Date addtime;

	// Constructors

	/** default constructor */
	public Myleague() {
	}

	/** minimal constructor */
	public Myleague(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Myleague(Integer id, String userId, String friendId,
			String friendName, Integer status, Date addtime) {
		this.id = id;
		this.userId = userId;
		this.friendId = friendId;
		this.friendName = friendName;
		this.status = status;
		this.addtime = addtime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFriendId() {
		return this.friendId;
	}

	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}

	public String getFriendName() {
		return this.friendName;
	}

	public void setFriendName(String friendName) {
		this.friendName = friendName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}