package com.done.model;

import java.util.Date;

/**
 * RelationHw generated by MyEclipse Persistence Tools
 */

public class RelationHw implements java.io.Serializable {

	// Fields

	private Integer relationId;

	private Integer hwId;

	private String relationHwId;

	private String relationHwName;

	private Date addtime;

	// Constructors

	/** default constructor */
	public RelationHw() {
	}

	/** minimal constructor */
	public RelationHw(Integer relationId) {
		this.relationId = relationId;
	}

	/** full constructor */
	public RelationHw(Integer relationId, Integer hwId, String relationHwId,
			String relationHwName, Date addtime) {
		this.relationId = relationId;
		this.hwId = hwId;
		this.relationHwId = relationHwId;
		this.relationHwName = relationHwName;
		this.addtime = addtime;
	}

	// Property accessors

	public Integer getRelationId() {
		return this.relationId;
	}

	public void setRelationId(Integer relationId) {
		this.relationId = relationId;
	}

	public Integer getHwId() {
		return this.hwId;
	}

	public void setHwId(Integer hwId) {
		this.hwId = hwId;
	}

	public String getRelationHwId() {
		return this.relationHwId;
	}

	public void setRelationHwId(String relationHwId) {
		this.relationHwId = relationHwId;
	}

	public String getRelationHwName() {
		return this.relationHwName;
	}

	public void setRelationHwName(String relationHwName) {
		this.relationHwName = relationHwName;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}