package com.done.model;

import java.util.Date;

/**
 * ShopDetail generated by MyEclipse Persistence Tools
 */

public class ShopDetail implements java.io.Serializable {

    // Fields

    private String userId;

    private String web;

    private String sitename;

    private String maddr;

    private String msn;

    private String mname;

    private String code;

    private String ymaddr;

    private String ymname;

    private Integer status;

    private String storeName;

    private Integer visitTimes;

    private Integer storeStatus;

    private Date modifyTime;

    private Date addtime;

    private String briefDesc;

    private String detailDesc;

    private String shopPic;

    private String colorStyle;

    //从UserDetail拷贝过来的属性
    private String userMail;

    private String userAdds;

    private String userTel;

    private String userPostcode;

    // Constructors

    /** default constructor */
    public ShopDetail() {
    }

    /** minimal constructor */
    public ShopDetail(String userId, Date modifyTime, Date addtime) {
        this.userId = userId;
        this.modifyTime = modifyTime;
        this.addtime = addtime;
    }

    public String getUserAdds() {
        return userAdds;
    }

    public void setUserAdds(String userAdds) {
        this.userAdds = userAdds;
    }

    public String getUserMail() {
        return userMail;
    }

    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    public String getUserPostcode() {
        return userPostcode;
    }

    public void setUserPostcode(String userPostcode) {
        this.userPostcode = userPostcode;
    }

    public String getUserTel() {
        return userTel;
    }

    public void setUserTel(String userTel) {
        this.userTel = userTel;
    }

    public ShopDetail(String userId, String web, String sitename, String maddr, String msn, String mname, String code,
            String ymaddr, String ymname, String storeName, Integer visitTimes, Date modifyTime, String userMail,
            String userTel, String userPostcode, String colorStyle, String briefDesc) {
        this.userId = userId;
        this.web = web;
        this.sitename = sitename;
        this.maddr = maddr;
        this.msn = msn;
        this.mname = mname;
        this.code = code;
        this.ymaddr = ymaddr;
        this.ymname = ymname;
        this.storeName = storeName;
        this.visitTimes = visitTimes;
        this.modifyTime = modifyTime;
        this.userMail = userMail;
        this.userTel = userTel;
        this.userPostcode = userPostcode;
        this.colorStyle = colorStyle;
        this.briefDesc = briefDesc;
    }

    /** full constructor */
    public ShopDetail(String userId, String web, String sitename, String maddr, String msn, String mname, String code,
            String ymaddr, String ymname, Integer status, String storeName, Integer visitTimes, Integer storeStatus,
            Date modifyTime, Date addtime) {
        this.userId = userId;
        this.web = web;
        this.sitename = sitename;
        this.maddr = maddr;
        this.msn = msn;
        this.mname = mname;
        this.code = code;
        this.ymaddr = ymaddr;
        this.ymname = ymname;
        this.status = status;
        this.storeName = storeName;
        this.visitTimes = visitTimes;
        this.storeStatus = storeStatus;
        this.modifyTime = modifyTime;
        this.addtime = addtime;
    }

    // Property accessors

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getWeb() {
        return this.web;
    }

    public void setWeb(String web) {
        this.web = web;
    }

    public String getSitename() {
        return this.sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public String getMaddr() {
        return this.maddr;
    }

    public void setMaddr(String maddr) {
        this.maddr = maddr;
    }

    public String getMsn() {
        return this.msn;
    }

    public void setMsn(String msn) {
        this.msn = msn;
    }

    public String getMname() {
        return this.mname;
    }

    public void setMname(String mname) {
        this.mname = mname;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getYmaddr() {
        return this.ymaddr;
    }

    public void setYmaddr(String ymaddr) {
        this.ymaddr = ymaddr;
    }

    public String getYmname() {
        return this.ymname;
    }

    public void setYmname(String ymname) {
        this.ymname = ymname;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getStoreName() {
        return this.storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public Integer getVisitTimes() {
        return this.visitTimes;
    }

    public void setVisitTimes(Integer visitTimes) {
        this.visitTimes = visitTimes;
    }

    public Integer getStoreStatus() {
        return this.storeStatus;
    }

    public void setStoreStatus(Integer storeStatus) {
        this.storeStatus = storeStatus;
    }

    public Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Date getAddtime() {
        return this.addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public String getBriefDesc() {
        return briefDesc;
    }

    public void setBriefDesc(String briefDesc) {
        this.briefDesc = briefDesc;
    }

    public String getDetailDesc() {
        return detailDesc;
    }

    public void setDetailDesc(String detailDesc) {
        this.detailDesc = detailDesc;
    }

    public String getShopPic() {
        return shopPic;
    }

    public void setShopPic(String shopPic) {
        this.shopPic = shopPic;
    }

    public String getColorStyle() {
        return colorStyle;
    }

    public void setColorStyle(String colorStyle) {
        this.colorStyle = colorStyle;
    }

}