package com.done.model;

import java.util.Date;

/**
 * Sub generated by MyEclipse Persistence Tools
 */

public class Sub implements java.io.Serializable {

    // Fields

    private Integer subId;

    private String basketId;

    private String userName;

    private String orderName;

    private Date subDate;

    private String subNumber;

    private String subCheck;

    private Double total;

    private String subMail;

    private String subTel;

    private Integer payId;

    private String subAdds;

    private String subPost;

    private String other;

    private String shopName;

    // Constructors

    /** default constructor */
    public Sub() {
    }

    /** minimal constructor */
    public Sub(Integer subId, String subNumber, Double total) {
        this.subId = subId;
        this.subNumber = subNumber;
        this.total = total;
    }

    /** full constructor */
    public Sub(Integer subId, String basketId, String userName, String orderName, Date subDate, String subNumber,
            String subCheck, Double total, String subMail, String subTel, Integer payId, String subAdds,
            String subPost, String other) {
        this.subId = subId;
        this.basketId = basketId;
        this.userName = userName;
        this.orderName = orderName;
        this.subDate = subDate;
        this.subNumber = subNumber;
        this.subCheck = subCheck;
        this.total = total;
        this.subMail = subMail;
        this.subTel = subTel;
        this.payId = payId;
        this.subAdds = subAdds;
        this.subPost = subPost;
        this.other = other;
    }

    // Property accessors

    public Integer getSubId() {
        return this.subId;
    }

    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    public String getBasketId() {
        return this.basketId;
    }

    public void setBasketId(String basketId) {
        this.basketId = basketId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getOrderName() {
        return this.orderName;
    }

    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    public Date getSubDate() {
        return this.subDate;
    }

    public void setSubDate(Date subDate) {
        this.subDate = subDate;
    }

    public String getSubNumber() {
        return this.subNumber;
    }

    public void setSubNumber(String subNumber) {
        this.subNumber = subNumber;
    }

    public String getSubCheck() {
        return this.subCheck;
    }

    public void setSubCheck(String subCheck) {
        this.subCheck = subCheck;
    }

    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public String getSubMail() {
        return this.subMail;
    }

    public void setSubMail(String subMail) {
        this.subMail = subMail;
    }

    public String getSubTel() {
        return this.subTel;
    }

    public void setSubTel(String subTel) {
        this.subTel = subTel;
    }

    public Integer getPayId() {
        return this.payId;
    }

    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    public String getSubAdds() {
        return this.subAdds;
    }

    public void setSubAdds(String subAdds) {
        this.subAdds = subAdds;
    }

    public String getSubPost() {
        return this.subPost;
    }

    public void setSubPost(String subPost) {
        this.subPost = subPost;
    }

    public String getOther() {
        return this.other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

}