package com.done.model;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String password;

	private String enabled;

	private String note;

	// Constructors

	/** default constructor */
	public TUser() {
	}

	/** minimal constructor */
	public TUser(String id, String name, String password, String enabled) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.enabled = enabled;
	}

	/** full constructor */
	public TUser(String id, String name, String password, String enabled,
			String note) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.enabled = enabled;
		this.note = note;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}