package com.done.model;

import java.util.Date;

/**
 * UserComment generated by MyEclipse Persistence Tools
 */

public class UserComment implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer commentType;

	private String userId;

	private String userName;

	private String yourName;

	private String toUserName;

	private String content;
	
	private String answer;

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	private Date addtime;
	
	private Date answertime;
	
	public Date getAnswertime() {
		return answertime;
	}

	public void setAnswertime(Date answertime) {
		this.answertime = answertime;
	}

	private String postip;

	private Integer status;

	// Constructors

	/** default constructor */
	public UserComment() {
	}

	/** minimal constructor */
	public UserComment(Integer id) {
		this.id = id;
	}


	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCommentType() {
		return this.commentType;
	}

	public void setCommentType(Integer commentType) {
		this.commentType = commentType;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getYourName() {
		return this.yourName;
	}

	public void setYourName(String yourName) {
		this.yourName = yourName;
	}

	public String getToUserName() {
		return this.toUserName;
	}

	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public String getPostip() {
		return this.postip;
	}

	public void setPostip(String postip) {
		this.postip = postip;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}