package com.done.model;

import java.util.Date;

/**
 * UserDetail generated by MyEclipse Persistence Tools
 */

public class UserDetail implements java.io.Serializable {

	// Fields

	private String userId;

	private Integer gradeId;

	private String userName;
	
	private String nickName;

	private String userMail;

	private String userAdds;

	private String userTel;

	private String userPostcode;

	private String msn;

	private String qq;

	private String fax;

	private Date modifyTime;

	private Date userRegtime;

	private String userRegip;

	private Date userLasttime;

	private String userLastip;

	private String userMemo;
	
	private String password;
	
	private ShopDetail shopDetail;

	// Constructors

	/** default constructor */
	public UserDetail() {
	}

	

	// Property accessors

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserMail() {
		return this.userMail;
	}

	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

	public String getUserAdds() {
		return this.userAdds;
	}

	public void setUserAdds(String userAdds) {
		this.userAdds = userAdds;
	}

	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public String getUserPostcode() {
		return this.userPostcode;
	}

	public void setUserPostcode(String userPostcode) {
		this.userPostcode = userPostcode;
	}

	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Date getUserRegtime() {
		return this.userRegtime;
	}

	public void setUserRegtime(Date userRegtime) {
		this.userRegtime = userRegtime;
	}

	public String getUserRegip() {
		return this.userRegip;
	}

	public void setUserRegip(String userRegip) {
		this.userRegip = userRegip;
	}

	public Date getUserLasttime() {
		return this.userLasttime;
	}

	public void setUserLasttime(Date userLasttime) {
		this.userLasttime = userLasttime;
	}

	public String getUserLastip() {
		return this.userLastip;
	}

	public void setUserLastip(String userLastip) {
		this.userLastip = userLastip;
	}

	public String getUserMemo() {
		return this.userMemo;
	}

	public void setUserMemo(String userMemo) {
		this.userMemo = userMemo;
	}

	public ShopDetail getShopDetail() {
		return shopDetail;
	}

	public void setShopDetail(ShopDetail shopDetail) {
		this.shopDetail = shopDetail;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}



	public String getPassword() {
		return password;
	}



	public void setPassword(String password) {
		this.password = password;
	}



}