package com.legendshop.ws.service.sub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-06T22:58:21.410+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "SubService", 
                  wsdlLocation = "http://localhost:81/legendshop_ws/services/subService?wsdl",
                  targetNamespace = "http://sub.service.ws.legendshop.com") 
public class SubService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sub.service.ws.legendshop.com", "SubService");
    public final static QName SubServicePort = new QName("http://sub.service.ws.legendshop.com", "SubServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:81/legendshop_ws/services/subService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SubService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:81/legendshop_ws/services/subService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SubService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SubService
     */
    @WebEndpoint(name = "SubServicePort")
    public SubService getSubServicePort() {
        return super.getPort(SubServicePort, SubService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubService
     */
    @WebEndpoint(name = "SubServicePort")
    public SubService getSubServicePort(WebServiceFeature... features) {
        return super.getPort(SubServicePort, SubService.class, features);
    }

}
