
package com.legendshop.ws.service.product;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.UUID;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-03T23:02:19.495+08:00
 * Generated source version: 2.6.1
 * 
 */
public final class ProductService_ProductServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://product.service.ws.legendshop.com", "ProductService");

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProductService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductService_Service ss = new ProductService_Service(wsdlURL, SERVICE_NAME);
        ProductService port = ss.getProductServicePort();  
        
        {
        System.out.println("Invoking importProductService...");
        com.legendshop.ws.service.product.Product product = new com.legendshop.ws.service.product.Product();
        product.setName("测试产品"+ UUID.randomUUID());
        product.setSortId(55l);
        product.setNsortId(236l);
        product.setSubNsortId(120l);
        product.setPrice(10000d);
        product.setCash(20000.12);
        product.setContent("content");
        product.setPic("360buy/hw/pb1.jpg");
        product.setCommend("Y");
        product.setBrandId(25l);
        
        String result = port.importProductService(product);
        System.out.println("importProductService.result=" + result);


        }

        System.exit(0);
    }

    private ProductService_ProductServicePort_Client() {
    }

}
