package com.legendshop.ws.service.product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-03T23:02:19.605+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://product.service.ws.legendshop.com", name = "productService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importProductService", targetNamespace = "http://product.service.ws.legendshop.com", className = "com.legendshop.ws.service.product.ImportProductService")
    @WebMethod
    @ResponseWrapper(localName = "importProductServiceResponse", targetNamespace = "http://product.service.ws.legendshop.com", className = "com.legendshop.ws.service.product.ImportProductServiceResponse")
    public java.lang.String importProductService(
        @WebParam(name = "product", targetNamespace = "")
        com.legendshop.ws.service.product.Product product
    );
}
