
package com.legendshop.ws.service.sub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-08-06T22:58:21.304+08:00
 * Generated source version: 2.6.1
 * 
 */
public final class SubService_SubServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://sub.service.ws.legendshop.com", "SubService");

    private SubService_SubServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SubService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SubService_Service ss = new SubService_Service(wsdlURL, SERVICE_NAME);
        SubService port = ss.getSubServicePort();  
        
        {
        System.out.println("Invoking exportOrderService...");
        com.legendshop.ws.service.sub.Sub _exportOrderService_sub = null;
        java.lang.String _exportOrderService__return = port.exportOrderService(_exportOrderService_sub);
        System.out.println("exportOrderService.result=" + _exportOrderService__return);


        }

        System.exit(0);
    }

}
